---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Kubectl get pods in json format
    kubectl: action=get type=pods output=wide
    register: output

  - debug: var=output.msg

  #- name: Kubectl get a single replication controller with specified name in ps output format.
    #kubectl: action=get type=rc name=web

  #- name: Kubectl get resources with type and  name specified in pods.yaml
    #kubectl: action=get file=pods.yaml output=json

  #- name: Kubectl get replication controllers and services together
    #kubectl: action=get type=rc,services output=json
