---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
      - name: Kubectl get details of a single pod with name rhgs-3
      kubectl: action=get type=pod name=rhgs-3
        register: output

      - debug: var=output.msg

