---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Kubectl exec on pod rhgs-2
    kubectl: action=exec pod=rhgs-2 command='date,echo "hi"'
    register: result

  - debug: var=result.msg



