---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
   - name: kubectl create pod from json input
     kubectl: action=create filename=rhgs-1.json

   - name: kubectl create pod from json input
     kubectl: action=create filename=rhgs-2.json
